import Head from 'next/head'
import { useQuery } from '@apollo/client'
import { useCookies } from 'react-cookie'
import { GET_LAUNCHES_LIST } from '@/common/queries/get-cards'
import { LaunchesList } from '@/common/LaunchesList'
import { LaunchCard } from '@/common/LaunchCard'
import { LaunchCardType } from '@/common/types/launch-card'
import styles from './styles/Bookmarks.module.css'

export default function Bookmarks() {
  const {data, loading, error} = useQuery(GET_LAUNCHES_LIST, {
    fetchPolicy: "no-cache",
    variables: {
      limit: null,
      offset: null
    }
  })

  const [cookies] = useCookies()

  const result = data?.launches?.filter((launch: LaunchCardType) => {
    if(Object.values(cookies).includes(launch.id)) {
      return launch
    }

    return
  })

  return (
    <>
      <Head>
        <title>Bookmarks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <LaunchesList>
        {loading && <span className={styles.span}>Loading...</span>}
        {error && <span className={styles.span}>Error while fetching data</span>}
        {result?.length === 0 && <span className={styles.span}>No bookmarks yet</span>}
        {result?.map((launch: LaunchCardType) => (
          <LaunchCard
            id={launch.id}
            key={launch.id}
            missionName={launch.mission_name}
            launchDate={launch.launch_date_unix}
            rocket={launch.rocket.rocket_name}
            details={launch.details}
            link={launch.links.presskit}
          />
        ))}
      </LaunchesList>
    </>
  )
}
